version: '3.8'

services:
  attack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  att:
    build:
      context: ./URL
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ab:
    build:
      context: ./ab
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  wrk:
    build: ./wrk
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


